### ISSUE TITLE
"NRZ-2020-129" - compile error  BearSSL

### ISSUE THREAD

**Issue by FrankUlbrich** [opendata-stuttgart/sensors-software#653]
Hello I tried to compile the airrohr firmware "NRZ-2020-129" 
from the master branch for NodeMCU 1.0 and I am getting the following error.

'Session' in namespace 'BearSSL' does not name a type
-----------------------------------------------------------------

In file included from C:\Users\HP\Dropbox\Frank\Downloads\arduino\projekte\WEMO_ESP\airrohr-firmware_2020\airrohr-firmware_2020.ino:156:0:

ext_def.h:48: error: 'Session' in namespace 'BearSSL' does not name a type

     BearSSL::Session* session;

Is there something what I could do to get rid of this compile error ?

I am running older Software compiled with ArduinoJson 5  and I would like to go to newer version with ArduinoJson 6.

Viele Gruesse
Frank

**Comment by ricki-z** [comment]
Could you please check the installed Arduino Core? This should be the version mentioned in the Readme.md.

**Comment by FrankUlbrich** [comment]
![image](https://user-images.githubusercontent.com/50796924/73481861-f30e9600-439c-11ea-86f0-67d2d4c03969.png)

Hi,
I am compiling wir ARDUINO IDE 1.8.3  and selected "NodeMCU 1.0" as target board. Not sure what happens. I tried the same with "Generic ESP3266" with the same result. In the past I  did not have problems with older versions.

![image](https://user-images.githubusercontent.com/50796924/73482206-8fd13380-439d-11ea-8239-3e58c266a971.png)

I will try it with a new GITHUB sanpshot.

**Comment by FrankUlbrich** [comment]
I tried it wit a fresh downloaded  master snapshot from today. 
Can anyone confirm or test if it really compiles with  NodeMCE 1.0  (ESP3266), please ?

**Comment by ricki-z** [comment]
What "Arduino Core for ESP8266" have you installed? This should work with 2.6.3, the latest stable release.

**Comment by FrankUlbrich** [comment]
ricki, thanks a lot for your hint. I didn't understand the meaning Arduino Core.
The compiler works now with the latest Arduino Core:
![image](https://user-images.githubusercontent.com/50796924/73579082-b799c780-4481-11ea-8fbc-69e4840a8b14.png)

This solved my probems, thanks a lot.

**Comment by FrankUlbrich** [comment]
Upgraded my IDE to esp3266 vore version  2.6.3

**Comment by FrankUlbrich** [comment]
Upgraded my IDE to esp3266 vore version  2.6.3
